[package]
name = "hello-world-cargo"
version = "0.1.0"
authors = ["cat <pierrick@live.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3"
